import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        'playfair': ['var(--font-playfair)', 'serif'],
        'poppins': ['var(--font-poppins)', 'sans-serif'],
        'source-sans': ['var(--font-source-sans)', 'sans-serif'],
        'inter': ['var(--font-inter)', 'sans-serif'],
        'manrope': ['var(--font-manrope)', 'sans-serif'],
        'bricolage': ['var(--font-bricolage)', 'Arial', 'sans-serif'],
        'albert': ['var(--font-albert)', 'Arial', 'sans-serif'],
      },
      colors: {
        brand: {
          ink: '#080d10',
          bone: '#fffefd',
          surface: '#272727',
          'ink-muted': 'rgba(8, 13, 16, 0.7)',
          'ink-soft': 'rgba(8, 13, 16, 0.4)',
          'ink-faint': 'rgba(8, 13, 16, 0.04)',
          'bone-muted': 'rgba(255, 254, 253, 0.6)',
          'bone-soft': 'rgba(255, 254, 253, 0.4)',
          'bone-faint': 'rgba(255, 255, 255, 0.08)',
          orange: '#590178',
          'orange-hover': '#4a0166',
          red: '#ff3d2e',
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        secondary: "hsl(var(--secondary))",
        "secondary-foreground": "hsl(var(--secondary-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        destructive: "hsl(var(--destructive))",
        "destructive-foreground": "hsl(var(--destructive-foreground))",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
      },
      fontSize: {
        'brand-display': ['clamp(2.75rem, 6vw, 5rem)', { lineHeight: '1.05', letterSpacing: '-0.02em' }],
        'brand-h2': ['clamp(2rem, 4.5vw, 4.25rem)', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
        'brand-h3': ['clamp(1.5rem, 2.2vw, 2rem)', { lineHeight: '1.3', letterSpacing: '-0.03em' }],
        'brand-h4': ['1.25rem', { lineHeight: '1.4', letterSpacing: '-0.01em' }],
        'brand-body-lg': ['1.125rem', { lineHeight: '1.6' }],
        'brand-body': ['1rem', { lineHeight: '1.5' }],
        'brand-caption': ['0.8125rem', { lineHeight: '1.4', letterSpacing: '0.06em' }],
      },
      borderRadius: {
        'brand-pill': '999px',
        'brand-btn': '12px',
        'brand-card': '12px',
        'brand-section': '40px',
      },
      maxWidth: {
        'brand-page': '1320px',
      },
      transitionTimingFunction: {
        'brand-out': 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
    },
  },
  plugins: [],
} satisfies Config;
